lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_id_claim: email
    token_ttl: 900 # tiempo de vida de 15 minutos
    api_platform:
        check_path: /api/login_check
        username_path: email
        password_path: password
    token_extractors:
        authorization_header:
            enabled: true
            prefix: Bearer
            name: Authorization
